server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      # 只执行 CREATE TABLE IF NOT EXISTS，不会覆盖老师提供的原始数据。
      mode: always
      encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

app:
  upload-dir: ${ADMIN_UPLOAD_DIR:uploads}

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: YWRtaW5TZWNyZXRLZXlGb3JTbWFydENvbW11bml0eTIwMjY=
  expiration: 86400000
